# Generated by Django 4.2.10 on 2026-04-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_alter_listing_options_listing_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('sberbank', 'Сбербанк'), ('card', 'Банковская карта'), ('mock', 'Тестовый режим')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sberbank_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_transactions', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Премиум транзакция',
                'verbose_name_plural': 'Премиум транзакции',
                'ordering': ['-created_at'],
            },
        ),
    ]
