# Generated by Django 4.2.10 on 2026-04-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEstimationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(help_text='Площадь в м²')),
                ('rooms', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField(default=5)),
                ('property_type', models.CharField(default='apartment', max_length=50)),
                ('home_type', models.CharField(default='Condo', max_length=50)),
                ('estimated_price', models.IntegerField()),
                ('confidence', models.FloatField(default=0.85)),
                ('is_premium_user', models.BooleanField(default=False)),
                ('discount_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_estimations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История AI оценки',
                'verbose_name_plural': 'Истории AI оценок',
                'ordering': ['-created_at'],
            },
        ),
    ]
